### ISSUE TITLE
[Wetmsm] ApplyComponents expected 'long' but got Python object

### ISSUE THREAD

**Issue by albumns** [msmbuilder/msmbuilder#569]
Hello,

I've installed the most recent version of  Wetmsm, and the command failed with messages:

```
1/msmb> msmb SolventApplyComponents --trjs md.xtc --top npt2.pdb --solvent_indices solvent.txt --solute_indices solute.txt --assignments waterassign --component tica_model.pkl --out watercomponent
```

```
ApplyComponents(agg_method=add,
component=[ 0.39314 0.00723 ..., 0.0195 0.00097],
solute_indices=['8' '15' ..., '5967' '5981'],
solvent_indices=['6063' '6066' ..., '76617' '76620'], stride=1)
/usr/lib64/python2.7/site-packages/WetMSM-0.3-py2.7-linux-x86_64.egg/wetmsm/vmd_write.py:173: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
user = np.zeros((ceil(traj.n_frames / self.stride), traj.n_atoms))
An unexpected error has occurred with MSMBuilder (version 3.3.0.dev0.dev-Unknown), please
consider sending the following traceback to MSMBuilder GitHub issue tracker at:
https://github.com/msmbuilder/msmbuilder/issues

Traceback (most recent call last):
File "/usr/bin/msmb", line 9, in 
load_entry_point('msmbuilder==3.3.0.dev0', 'console_scripts', 'msmb')()
File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/scripts/msmb.py", line 28, in main
app.start()
File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/cmdline.py", line 440, in start
instance.start()
File "/usr/lib64/python2.7/site-packages/WetMSM-0.3-py2.7-linux-x86_64.egg/wetmsm/vmd_write.py", line 331, in start
(traj_dataset[tr_key], assn_dataset[as_key])
File "/usr/lib64/python2.7/site-packages/WetMSM-0.3-py2.7-linux-x86_64.egg/wetmsm/vmd_write.py", line 194, in partial_transform
self.stride)
File "wetmsm/_vmd_write.pyx", line 56, in wetmsm._vmd_write._compute_chunk_add (wetmsm/_vmd_write.c:2098)
ValueError: Buffer dtype mismatch, expected 'long' but got Python object
```

@mpharrigan
@rmcgibbo

**Comment by mpharrigan** [comment]
This issue was fixed in mpharrigan/wetmsm#10 

You can either (1) re-run the "Assignment" step or (2) cast the assignment array to `int`:
```python
from msmbuilder.dataset import dataset
ds_in = dataset("waterassign")
ds_out = ds_in.create_derived("waterassign_fixed")
for i in ds_in.keys():
   ds_out[i] = np.asarray(ds_in[i], dtype=np.int)
```
(There may be some syntax problems in that code, I just wrote it from the top of my head)

**Comment by albumns** [comment]
Thank you for the reply.

I tried (1) re-run the "assignment" and the same error is still there

(2) which exact python script you were mentioning? Would you please tell me the path of it?

Thanks again. 

@mpharrigan

**Comment by mpharrigan** [comment]
(2) is just the code I posted in the comment

I'm investigating the code. This could be related to mpharrigan/wetmsm#10 but in a different place. I developed on python 3 and then used the `future` package to make it work in python 2, but it seems to be causing problems

**Comment by mpharrigan** [comment]
Actually this is the problem:
```
solute_indices=['8' '15' ..., '5967' '5981'],
solvent_indices=['6063' '6066' ..., '76617' '76620'], stride=1)
```

The indices are getting parsed as strings.

Can you post a small excerpt of `solvent.txt`

**Comment by mpharrigan** [comment]
Actually I could reproduce this and have implemented a fix:

mpharrigan/wetmsm#14
